// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models.Context;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ElectionContext))]
    [Migration("20240304073910_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Election", b =>
                {
                    b.Property<int>("UpdatedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpdatedId"));

                    b.Property<double>("Candidate2")
                        .HasColumnType("float");

                    b.Property<double>("Condidate1")
                        .HasColumnType("float");

                    b.HasKey("UpdatedId");

                    b.ToTable("Elections");
                });
#pragma warning restore 612, 618
        }
    }
}
